[package]
name = "ccmath"
description = "A simple library for doing math with complex numbers"
version = "1.0.0"
edition = "2024"
license = "MIT"
keywords = ["mathematics", "complex"]
repository = "https://github.com/Definitely-Not-A-Dolphin/CCMath"
readme = "README.md"
authors = ["Derek Verduijn"]

[dependencies]
approx = "0.5.1"
num-traits = "0.2.19"
